### ISSUE TITLE
Preparing the E2E environment

### ISSUE THREAD

**Issue by 3100** [datachainlab/harmony-cosmos-bridge-demo#9]
As an E2E environment during development, we will be able to check up to Handshake at IBC first.
- [x] tendermint local network #13
- [x] harmony local network #12 
- [x] relayer config #13 
- [x] test scripts for handshake #13

**Comment by 3100** [comment]
- [x] We will configure CI to complete E2E on github actions.
